### PR TITLE
adding lib to handle monochrome image filter. adding monochrome button

### PR DESCRIPTION
**Pull request by seal62**
PR for https://github.com/dodie/tracing-paper-sketching/issues/61

react-native-color-matrix-image-filters will handle converting the image to monochrome (https://github.com/iyegoroff/react-native-color-matrix-image-filters)

I added the button but currently using the same icon as the brightness button (which wasnt in your screenshot of the issue so I just left the monochrome button above this one).

### CODE REVIEW

**Comment by dodie** [comment]
Hi @seal62 ,
Thank you!

I tried it, but I got the following error when I started the app using `yarn start`, and tapped on the Monochrome button:
```
Warning: %s: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI., RootErrorBoundary
- node_modules/expo/build/environment/muteWarnings.fx.js:26:24 in error
- ... 25 more stack frames from framework internals

Invariant Violation: requireNativeComponent: "CMIFColorMatrixImageFilter" was not found in the UIManager.
- node_modules/react-native/Libraries/ReactNative/getNativeComponentAttributes.js:29:4 in getNativeComponentAttributes
- node_modules/react-native/Libraries/Renderer/shims/ReactNativeViewConfigRegistry.js:104:25 in get
- ... 18 more stack frames from framework internals
```

I've tested it running the dev mode on Windows and Ubuntu 16.04, in both cases I got the same error. 

Seems like this issue might be related: https://github.com/iyegoroff/react-native-color-matrix-image-filters/issues/14

Do you experience the same error?

Cheers,
David

**Comment by seal62** [comment]
Hi @dodie hmmm no I didnt see this error, did you install and link the module correctly? Ill take a look over the weekend, see if I can repo

**Comment by dodie** [comment]
I don't think it's possible to link modules for expo apps, so I did not try linking. After your suggestion I also tried the following:

```
react-native link react-native-color-matrix-image-filters
```
But it did not help. Is this the command you've used?
Thanks!

**Comment by seal62** [comment]
I tested on iOS, could very likely be why. Let me take a look and I’ll update the PR with a better solution.

**Comment by dodie** [comment]
It seems that react-native-color-matrix-image-filters is not working with Expo, so unless we eject the app, which would drastically change developer experience. Therefore, I'll close this PR without merging.

**Pull request closed without merging**
